title: "Prange Lab"
email: "info@prangelab.org"
description: "Epigenetic and transcriptional regulation in cardiometabolic disease"
url: "https://prangelab.org"   # custom domain
baseurl: ""                    # must stay empty for orgname.github.io root

theme: jekyll-theme-slate
github_username: prangelab

sass:
  sass_dir: assets/css

nav:
  - name: Home
    link: /
  - name: Research
    link: /research
  - name: Publications
    link: /publications
  - name: Team
    link: /team
  - name: Contact
    link: /contact
