title: "Prange Lab"
email: "info@prangelab.org"
description: "Epigenetic and transcriptional regulation in cardiometabolic disease"
url: "https://prangelab.org"
baseurl: ""

theme: jekyll-theme-cayman
github_username: prangelab
